config/routes.rb
DemoApp::Application.routes.draw do
  resources :tweets

  resources :microposts

  resources :useroks

  resources :users

end

app/models/userok.rb
class Userok < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/useroks_controller.rb
class UseroksController < ApplicationController
  # GET /useroks
  # GET /useroks.json
  def index
    @useroks = Userok.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @useroks }
    end
  end

  # GET /useroks/1
  # GET /useroks/1.json
  def show
    @userok = Userok.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @userok }
    end
  end

  # GET /useroks/new
  # GET /useroks/new.json
  def new
    @userok = Userok.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @userok }
    end
  end

  # GET /useroks/1/edit
  def edit
    @userok = Userok.find(params[:id])
  end

  # POST /useroks
  # POST /useroks.json
  def create
    @userok = Userok.new(params[:userok])

    respond_to do |format|
      if @userok.save
        format.html { redirect_to @userok, notice: 'Userok was successfully created.' }
        format.json { render json: @userok, status: :created, location: @userok }
      else
        format.html { render action: "new" }
        format.json { render json: @userok.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /useroks/1
  # PUT /useroks/1.json
  def update
    @userok = Userok.find(params[:id])

    respond_to do |format|
      if @userok.update_attributes(params[:userok])
        format.html { redirect_to @userok, notice: 'Userok was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @userok.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /useroks/1
  # DELETE /useroks/1.json
  def destroy
    @userok = Userok.find(params[:id])
    @userok.destroy

    respond_to do |format|
      format.html { redirect_to useroks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/useroks_helper.rb
module UseroksHelper
end

app/views/useroks/_form.html.erb
<%= form_for(@userok) do |f| %>
  <% if @userok.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userok.errors.count, "error") %> prohibited this userok from being saved:</h2>

      <ul>
      <% @userok.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/useroks/edit.html.erb
<h1>Editing userok</h1>

<%= render 'form' %>

<%= link_to 'Show', @userok %> |
<%= link_to 'Back', useroks_path %>

app/views/useroks/index.html.erb
<h1>Listing useroks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @useroks.each do |userok| %>
  <tr>
    <td><%= userok.name %></td>
    <td><%= userok.email %></td>
    <td><%= link_to 'Show', userok %></td>
    <td><%= link_to 'Edit', edit_userok_path(userok) %></td>
    <td><%= link_to 'Destroy', userok, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Userok', new_userok_path %>

app/views/useroks/new.html.erb
<h1>New userok</h1>

<%= render 'form' %>

<%= link_to 'Back', useroks_path %>

app/views/useroks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @userok.name %>
</p>

<p>
  <b>Email:</b>
  <%= @userok.email %>
</p>


<%= link_to 'Edit', edit_userok_path(@userok) %> |
<%= link_to 'Back', useroks_path %>